# Environment Configuration
env: stag_hunt
type: PP4a

is_mp: False

# Model Parameters
state_dim: 79        # Dimension of the state space
action_dim: 6        # Dimension of the action space
agent_num: 2
max_action: 1.0      # Maximum action value
max_ep_len: 401                  # Maximum episode length

seq_len: 1

rtg_hidden_dim: 128
ReconGoal_hidden_dim: 128
StateEncoder_hidden_dim: 256
StateEncoder_num_heads: 4
embed_dim: 128
goal_step: 1

# DiT para
ALT_hidden_dim: 128
ALT_depth: 2
ALT_mlp_ratio: 2.0
cfg_scale: 1.4
lr: 0.001                      # Learning rate for optimizer
batch_size: 128                # Batch size for training

# Diffusion Parameters
dropout_rate: 0.2
n_timesteps: 30     # Number of timesteps for diffusion process
schedule_type: 'uniform'  # Schedule for noise
beta_min: 0.001
beta_max: 0.2
optimizer: 'AdamW'

num_epochs: 20                 # Number of training epochs
device: cuda                  # Device to use (cuda or cpu)

sample_num: 60                  # Number of samples for diffusion
beta: 0.0001                     # Rtg损失的系数
gamma: 0.2                    # ReconGoal损失的系数
lambda_aux: 0.1

# Data Parameters
train_data_path: "./data/overcooked_episodes_datas.pt"

# Testing and Saving Parameters
test_interval: 2               # Interval for testing
save_interval: 2               # Interval for saving model

model_save_path: "models"       # Directory to save models
